import { CardType } from "../type/card";

const path = "../assets/cardImages";

export const Deck: CardType[] = [
  {
    id: "AC",
    rank: 14,
    suit: "C",
    src: require(path + "/AC.png"),
  },
  {
    id: "AD",
    rank: 14,
    suit: "D",
    src: require(path + "/AD.png"),
  },
  {
    id: "AH",
    rank: 14,
    suit: "H",
    src: require(path + "/AH.png"),
  },
  {
    id: "AS",
    rank: 14,
    suit: "S",
    src: require(path + "/AS.png"),
  },
  {
    id: "KC",
    rank: 13,
    suit: "C",
    src: require(path + "/KC.png"),
  },
  {
    id: "KD",
    rank: 13,
    suit: "D",
    src: require(path + "/KD.png"),
  },
  {
    id: "KH",
    rank: 13,
    suit: "H",
    src: require(path + "/KH.png"),
  },
  {
    id: "KS",
    rank: 13,
    suit: "S",
    src: require(path + "/KS.png"),
  },
  {
    id: "QC",
    rank: 12,
    suit: "C",
    src: require(path + "/QC.png"),
  },
  {
    id: "QD",
    rank: 12,
    suit: "D",
    src: require(path + "/QD.png"),
  },
  {
    id: "QH",
    rank: 12,
    suit: "H",
    src: require(path + "/QH.png"),
  },
  {
    id: "QS",
    rank: 12,
    suit: "S",
    src: require(path + "/QS.png"),
  },
  {
    id: "JC",
    rank: 11,
    suit: "C",
    src: require(path + "/JC.png"),
  },
  {
    id: "JD",
    rank: 11,
    suit: "D",
    src: require(path + "/JD.png"),
  },
  {
    id: "JH",
    rank: 11,
    suit: "H",
    src: require(path + "/JH.png"),
  },
  {
    id: "JS",
    rank: 11,
    suit: "S",
    src: require(path + "/JS.png"),
  },
  {
    id: "10C",
    rank: 10,
    suit: "C",
    src: require(path + "/10C.png"),
  },
  {
    id: "10D",
    rank: 10,
    suit: "D",
    src: require(path + "/10D.png"),
  },
  {
    id: "10H",
    rank: 10,
    suit: "H",
    src: require(path + "/10H.png"),
  },
  {
    id: "10S",
    rank: 10,
    suit: "S",
    src: require(path + "/10S.png"),
  },
  {
    id: "9C",
    rank: 9,
    suit: "C",
    src: require(path + "/9C.png"),
  },
  {
    id: "9D",
    rank: 9,
    suit: "D",
    src: require(path + "/9D.png"),
  },
  {
    id: "9H",
    rank: 9,
    suit: "H",
    src: require(path + "/9H.png"),
  },
  {
    id: "9S",
    rank: 9,
    suit: "S",
    src: require(path + "/9S.png"),
  },
  {
    id: "8C",
    rank: 8,
    suit: "C",
    src: require(path + "/8C.png"),
  },
  {
    id: "8D",
    rank: 8,
    suit: "D",
    src: require(path + "/8D.png"),
  },
  {
    id: "8H",
    rank: 8,
    suit: "H",
    src: require(path + "/8H.png"),
  },
  {
    id: "8S",
    rank: 8,
    suit: "S",
    src: require(path + "/8S.png"),
  },
  {
    id: "7C",
    rank: 7,
    suit: "C",
    src: require(path + "/7C.png"),
  },
  {
    id: "7D",
    rank: 7,
    suit: "D",
    src: require(path + "/7D.png"),
  },
  {
    id: "7H",
    rank: 7,
    suit: "H",
    src: require(path + "/7H.png"),
  },
  {
    id: "7S",
    rank: 7,
    suit: "S",
    src: require(path + "/7S.png"),
  },
  {
    id: "6C",
    rank: 6,
    suit: "C",
    src: require(path + "/6C.png"),
  },
  {
    id: "6D",
    rank: 6,
    suit: "D",
    src: require(path + "/6D.png"),
  },
  {
    id: "6H",
    rank: 6,
    suit: "H",
    src: require(path + "/6H.png"),
  },
  {
    id: "6S",
    rank: 6,
    suit: "S",
    src: require(path + "/6S.png"),
  },
  {
    id: "5C",
    rank: 5,
    suit: "C",
    src: require(path + "/5C.png"),
  },
  {
    id: "5D",
    rank: 5,
    suit: "D",
    src: require(path + "/5D.png"),
  },
  {
    id: "5H",
    rank: 5,
    suit: "H",
    src: require(path + "/5H.png"),
  },
  {
    id: "5S",
    rank: 5,
    suit: "S",
    src: require(path + "/5S.png"),
  },
  {
    id: "4C",
    rank: 4,
    suit: "C",
    src: require(path + "/4C.png"),
  },
  {
    id: "4D",
    rank: 4,
    suit: "D",
    src: require(path + "/4D.png"),
  },
  {
    id: "4H",
    rank: 4,
    suit: "H",
    src: require(path + "/4H.png"),
  },
  {
    id: "4S",
    rank: 4,
    suit: "S",
    src: require(path + "/4S.png"),
  },
  {
    id: "3C",
    rank: 3,
    suit: "C",
    src: require(path + "/3C.png"),
  },
  {
    id: "3D",
    rank: 3,
    suit: "D",
    src: require(path + "/3D.png"),
  },
  {
    id: "3H",
    rank: 3,
    suit: "H",
    src: require(path + "/3H.png"),
  },
  {
    id: "3S",
    rank: 3,
    suit: "S",
    src: require(path + "/3S.png"),
  },
  {
    id: "2C",
    rank: 2,
    suit: "C",
    src: require(path + "/2C.png"),
  },
  {
    id: "2D",
    rank: 2,
    suit: "D",
    src: require(path + "/2D.png"),
  },
  {
    id: "2H",
    rank: 2,
    suit: "H",
    src: require(path + "/2H.png"),
  },
  {
    id: "2S",
    rank: 2,
    suit: "S",
    src: require(path + "/2S.png"),
  },
];